# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Quality Check Master and Publish

on:
  push:
    branches: [ feature/ci-2 ]

jobs:
  check-and-publish:
    name: "Quality Check Master and Publish"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout source code"
        uses: actions/checkout@v2
      - name: "Setup Node.js"
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: "Install node_modules"
        run: npm ci
      - name: "Build package"
        run: npm run build
      - name: "Run test"
        run: npm test
      - name: "Run lint"
        run: npm run lint
      - name: "Set git creds"
        run: "git config --global user.email 'you@example.com'"
        run: "git config --global user.name 'System Bump'"
      - name: "Increase path version"
        run: "npm version patch"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
      - name: "Update branch"
        run: "git push --follow-tags"
